#Minecraft server properties
#rldyourmcrft Server

# Network
server-port=25565
server-ip=
query.port=25565
enable-query=false
enable-rcon=false
rcon.port=25575
rcon.password=

# World
level-name=world
level-seed=
level-type=DEFAULT
generator-settings=
generate-structures=true
max-world-size=29999984
spawn-protection=16

# Gameplay
gamemode=0
difficulty=2
hardcore=false
pvp=true
allow-nether=true
allow-flight=false
enable-command-block=true
force-gamemode=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true

# Players
max-players=20
white-list=false
online-mode=true
player-idle-timeout=0
op-permission-level=4

# Performance
view-distance=10
max-tick-time=60000
network-compression-threshold=256
max-build-height=256
use-native-transport=true

# Misc
motd=rldyourmcrft Server
resource-pack=
resource-pack-sha1=
prevent-proxy-connections=false
snooper-enabled=false
